name: CI -- Docs

on:
  push:
    branches: [main]
    paths: ["docs/**", "spec/**"]
  pull_request:
    paths: ["docs/**", "spec/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Install MkDocs
        run: uv pip install mkdocs-material --system
      - name: Build docs
        working-directory: docs
        run: mkdocs build --strict
